### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by hirbod** [BenJeau/react-native-draw#32]
Hi,

looks great so far. Some ideas:

- Be able to add stickers (or images).
Make them scalable (pinch, rotate etc)

- be able to add multiple Text fields (maybe with color, scaling, rotating etc).

I’ve tried something similar like this before in the past but wasn’t really happy with my feature set and results , but your current development looks pretty neat

**Comment by BenJeau** [comment]
Hi @Hirbod, that would be cool features to add, although this is focused on drawing and the implementation is based on SVG views, we can _maybe_ add non-vector things like images and text (or vector text with SVG).

This is not something I see myself implementing for the foreseeable future (as I'm in school and have other occupations). If you want to implement something like this for this library, please let me know and I can maybe guide you on how to do it - but it will probably need a lot of work, since the code in this library is only displaying vector lines at the moment without any kind of transformation (rotation, scaling). Adding shapes and things available in SVG is probably the easiest to implement

**Comment by BenJeau** [comment]
Closing this issue as I don't see myself add these features and there's no response since my last comment
