### ISSUE TITLE
Function which return bitmap image in base64 format.

### ISSUE THREAD

**Issue by Anubhavshakya** [BenJeau/react-native-draw#53]
### Desired solution (feature)

I am able to convert the svg into base64 but I need a bitmap image as a base64 format.

**Comment by BenJeau** [comment]
I don't intend on adding rasterization support for this library, since this is something I'm unsure of how it works. But if you find a way on how to do it, I would gladly accept a PR or add it to the README :)

I see three ways to accomplish this:
1. React Native view capture, like this library https://www.npmjs.com/package/react-native-view-shot

Or rasterize the svg to a png (or other format) with something like https://www.npmjs.com/package/svg-png-converter, in
1. React Native (although I am unsure if these libs would work in React Native) there _must_ be a way to rasterize svg's in React Native, but do not know of a way
1. In a server, requesting the conversion and doing the conversion on the server

**Comment by Anubhavshakya** [comment]
Yes, React native capture solved my problem.
